#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DroidDesk Türkçeleştirme + Tüm Depolar yaması
=============================================
Depo kök dizininde çalıştırın:  python3 turkcelestir.py

- Dosyaların üzerine yazmaz; yalnızca bilinen metinleri bulup değiştirir.
  Bu sayede depoda yaptığınız başka değişiklikler korunur.
- Birden fazla kez çalıştırmak güvenlidir (uygulanmış değişiklikler atlanır).
- Bulunamayan metinler raporlanır ama derleme durdurulmaz.
"""
import os, sys

# (dosya, eski metin, yeni metin) — arayüz çevirileri
CEVIRILER = [('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '?: "Trackpad"', '?: "Dokunmatik yüzey"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', 'controlButton("Keyboard")', 'controlButton("Klavye")'),
    ('app/lib/screens/welcome_screen.dart', "'Switch to Light Theme'", "'Açık temaya geç'"),
    ('app/lib/screens/welcome_screen.dart', "'Switch to Dark Theme'", "'Koyu temaya geç'"),
    ('app/lib/screens/welcome_screen.dart', "'Full Linux Desktop on Android'", "'Android\\'de Tam Linux Masaüstü'"),
    ('app/lib/screens/welcome_screen.dart', "'Ubuntu · XFCE Desktop · Single App'", "'Ubuntu · XFCE Masaüstü · Tek Uygulama'"),
    ('app/lib/screens/welcome_screen.dart', "'Containerized'", "'Konteyner Tabanlı'"),
    ('app/lib/screens/welcome_screen.dart', "'Root Optional'", "'Root İsteğe Bağlı'"),
    ('app/lib/screens/welcome_screen.dart', "'Linux Desktop'", "'Linux Masaüstü'"),
    ('app/lib/screens/welcome_screen.dart', "'Local Execution'", "'Yerel Çalıştırma'"),
    ('app/lib/screens/welcome_screen.dart', "'Set Up Desktop Essentials'", "'Masaüstü Kurulumuna Başla'"),
    ('app/lib/screens/home_screen.dart', "'Desktop Running'", "'Masaüstü Çalışıyor'"),
    ('app/lib/screens/home_screen.dart', "'Ready'", "'Hazır'"),
    ('app/lib/screens/home_screen.dart', "'Switch to Light Theme'", "'Açık temaya geç'"),
    ('app/lib/screens/home_screen.dart', "'Switch to Dark Theme'", "'Koyu temaya geç'"),
    ('app/lib/screens/home_screen.dart', "'QUICK ACTIONS'", "'HIZLI İŞLEMLER'"),
    ('app/lib/screens/home_screen.dart', "'Install ${state.selectedDE.toUpperCase()}'", "'${state.selectedDE.toUpperCase()} Kur'"),
    ('app/lib/screens/home_screen.dart', "'Install desktop environment packages (one-time setup)'", "'Masaüstü ortamı paketlerini kur (tek seferlik kurulum)'"),
    ('app/lib/screens/home_screen.dart', "'Return to Desktop'", "'Masaüstüne Dön'"),
    ('app/lib/screens/home_screen.dart', "'${state.selectedDE.toUpperCase()} is currently running in background'", "'${state.selectedDE.toUpperCase()} şu anda arka planda çalışıyor'"),
    ('app/lib/screens/home_screen.dart', "'Stop Server'", "'Sunucuyu Durdur'"),
    ('app/lib/screens/home_screen.dart', "'Launch Desktop'", "'Masaüstünü Başlat'"),
    ('app/lib/screens/home_screen.dart', "'Shutdown Linux environment'", "'Linux ortamını kapat'"),
    ('app/lib/screens/home_screen.dart', "'Start ${state.selectedDE.toUpperCase()} desktop environment'", "'${state.selectedDE.toUpperCase()} masaüstü ortamını başlat'"),
    ('app/lib/screens/home_screen.dart', "'No Desktop Environment installed. Please complete setup first.'", "'Kurulu bir masaüstü ortamı yok. Lütfen önce kurulumu tamamlayın.'"),
    ('app/lib/screens/home_screen.dart', "'Open a Linux shell in the ${state.hasRoot ? 'Ubuntu chroot' : 'native Termux'} environment'", "'${state.hasRoot ? 'Ubuntu chroot' : 'yerel Termux'} ortamında bir Linux kabuğu aç'"),
    ('app/lib/screens/home_screen.dart', "'Debian shell'", "'Debian kabuğu'"),
    ('app/lib/screens/home_screen.dart', "'Open the optional minimal PRoot compatibility environment'", "'İsteğe bağlı minimal PRoot uyumluluk ortamını aç'"),
    ('app/lib/screens/home_screen.dart', "'Add applications'", "'Uygulama ekle'"),
    ('app/lib/screens/home_screen.dart', "'Install applications or optional Debian compatibility'", "'Uygulama ya da isteğe bağlı Debian uyumluluğu kur'"),
    ('app/lib/screens/home_screen.dart', "'SYSTEM'", "'SİSTEM'"),
    ('app/lib/screens/home_screen.dart', "'Distribution'", "'Dağıtım'"),
    ('app/lib/screens/home_screen.dart', "_infoRow('Desktop',", "_infoRow('Masaüstü',"),
    ('app/lib/screens/home_screen.dart', "'Renderer'", "'Oluşturucu'"),
    ('app/lib/screens/home_screen.dart', "'Automatic'", "'Otomatik'"),
    ('app/lib/screens/home_screen.dart', "'Device'", "'Cihaz'"),
    ('app/lib/screens/home_screen.dart', "'Storage Free'", "'Boş Depolama'"),
    ('app/lib/screens/home_screen.dart', "'Desktop Active'", "'Masaüstü Etkin'"),
    ('app/lib/screens/home_screen.dart', "'Desktop Idle'", "'Masaüstü Boşta'"),
    ('app/lib/screens/home_screen.dart', '\'Tap "Launch Desktop" to start\'', '\'Başlatmak için "Masaüstünü Başlat"a dokunun\''),
    ('app/lib/screens/home_screen.dart', "'Termux Native'", "'Yerel Termux'"),
    ('app/lib/screens/home_screen.dart', "'Settings'", "'Ayarlar'"),
    ('app/lib/screens/home_screen.dart', "'App Theme'", "'Uygulama Teması'"),
    ('app/lib/screens/home_screen.dart', "'System Default'", "'Sistem Varsayılanı'"),
    ('app/lib/screens/home_screen.dart', "'Dark Theme'", "'Koyu Tema'"),
    ('app/lib/screens/home_screen.dart', "'Light Theme'", "'Açık Tema'"),
    ('app/lib/screens/home_screen.dart', "Text('Dark')", "Text('Koyu')"),
    ('app/lib/screens/home_screen.dart', "Text('Light')", "Text('Açık')"),
    ('app/lib/screens/home_screen.dart', "Text('System')", "Text('Sistem')"),
    ('app/lib/screens/home_screen.dart', "'Battery Optimization'", "'Pil Optimizasyonu'"),
    ('app/lib/screens/home_screen.dart', "'Disable to prevent session killing'", "'Oturumun kapatılmasını önlemek için devre dışı bırakın'"),
    ('app/lib/screens/home_screen.dart', "'Set as default launcher'", "'Varsayılan başlatıcı yap'"),
    ('app/lib/screens/home_screen.dart', "'Open the Linux desktop when the phone starts'", "'Telefon açıldığında Linux masaüstünü aç'"),
    ('app/lib/screens/home_screen.dart', "'Stop using as default launcher'", "'Varsayılan başlatıcı olmaktan çıkar'"),
    ('app/lib/screens/home_screen.dart', "'Choose another Home app directly'", "'Doğrudan başka bir Ana Ekran uygulaması seç'"),
    ('app/lib/screens/home_screen.dart', "'Desktop Tools'", "'Masaüstü Araçları'"),
    ('app/lib/screens/home_screen.dart', "'Manage dock apps and desktop backups'", "'Dock uygulamalarını ve masaüstü yedeklerini yönet'"),
    ('app/lib/screens/home_screen.dart', "'Reinstall Linux'", "'Linux\\'u Yeniden Kur'"),
    ('app/lib/screens/home_screen.dart', "'Re-download and set up rootfs'", "'Rootfs\\'i yeniden indir ve kur'"),
    ('app/lib/screens/home_screen.dart', "'Change default launcher?'", "'Varsayılan başlatıcı değiştirilsin mi?'"),
    ('app/lib/screens/home_screen.dart', "'DroidDesk will stop opening automatically as your Home app. Android will ask you to choose another launcher.'", "'DroidDesk artık Ana Ekran uygulamanız olarak otomatik açılmayacak. Android sizden başka bir başlatıcı seçmenizi isteyecek.'"),
    ('app/lib/screens/home_screen.dart', "'Cancel'", "'İptal'"),
    ('app/lib/screens/home_screen.dart', "'Change launcher'", "'Başlatıcıyı değiştir'"),
    ('app/lib/screens/home_screen.dart', "'\\n^C (Command interrupted)\\n'", "'\\n^C (Komut kesildi)\\n'"),
    ('app/lib/screens/home_screen.dart', "'Interrupt Command (Ctrl+C)'", "'Komutu Kes (Ctrl+C)'"),
    ('app/lib/screens/home_screen.dart', "'compat · Debian PRoot'", "'uyumluluk · Debian PRoot'"),
    ('app/lib/screens/home_screen.dart', "'native · Termux/TUR'", "'yerel · Termux/TUR'"),
    ('app/lib/screens/home_screen.dart', "'Enter command...'", "'Komut girin...'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Fast, private desktop web browser.'", "'Hızlı ve gizlilik odaklı masaüstü web tarayıcısı.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Powerful desktop code editor and IDE.'", "'Güçlü masaüstü kod düzenleyici ve IDE.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Documents, spreadsheets, and presentations.'", "'Belgeler, hesap tabloları ve sunumlar.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Professional image editing and design tools.'", "'Profesyonel görüntü düzenleme ve tasarım araçları.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Complete open-source 3D creation suite.'", "'Eksiksiz, açık kaynaklı 3B oluşturma paketi.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Play almost every audio and video format.'", "'Neredeyse tüm ses ve video biçimlerini oynatır.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'JavaScript runtime and package manager.'", "'JavaScript çalışma ortamı ve paket yöneticisi.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Popular programming language and tools.'", "'Popüler programlama dili ve araçları.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Image conversion and processing toolkit.'", "'Görüntü dönüştürme ve işleme araç seti.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Preparing $packageName...'", "'$packageName hazırlanıyor...'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'$packageName installation cancelled'", "'$packageName kurulumu iptal edildi'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'$packageName installed'", "'$packageName kuruldu'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'$packageName installation failed'", "'$packageName kurulamadı'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Cancelling installation...'", "'Kurulum iptal ediliyor...'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Remove ${package.displayName}?'", "'${package.displayName} kaldırılsın mı?'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Dependent packages may also be affected.'", "'Buna bağımlı paketler de etkilenebilir.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Cancel'", "'İptal'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Remove'", "'Kaldır'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Preparing removal...'", "'Kaldırma işlemi hazırlanıyor...'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'${package.displayName} removed'", "'${package.displayName} kaldırıldı'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Removal failed'", "'Kaldırma başarısız oldu'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Linux App Store'", "'Linux Uygulama Mağazası'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Featured'", "'Öne Çıkanlar'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Browse'", "'Göz At'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Installed'", "'Kurulu'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Debian Compatibility'", "'Debian Uyumluluğu'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Run packages unavailable in native repositories.'", "'Yerel depolarda bulunmayan paketleri çalıştırın.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Popular Linux applications'", "'Popüler Linux uygulamaları'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Hand-picked apps tested for DroidDesk.'", "'DroidDesk için test edilmiş, özenle seçilmiş uygulamalar.'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Search packages, apps, and tools'", "'Paket, uygulama ve araç ara'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'No matching packages found'", "'Eşleşen paket bulunamadı'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'No packages installed yet'", "'Henüz kurulu paket yok'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Linux package'", "'Linux paketi'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'GUI app'", "'Grafik uygulama'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "Text('Install')", "Text('Kur')"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Cancelling'", "'İptal ediliyor'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'Cancel installation'", "'Kurulumu iptal et'"),
    ('app/lib/screens/apps/app_catalog_screen.dart', "'System'", "'Sistem'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Dock updated'", "'Dock güncellendi'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Could not update dock'", "'Dock güncellenemedi'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Desktop snapshot created'", "'Masaüstü anlık görüntüsü oluşturuldu'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Snapshot failed: $error'", "'Anlık görüntü alınamadı: $error'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Restore this snapshot?'", "'Bu anlık görüntü geri yüklensin mi?'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'The Linux session will stop. Current home files and settings will be replaced, and missing packages will be restored.'", "'Linux oturumu durdurulacak. Ev dizinindeki mevcut dosyalar ve ayarlar değiştirilecek, eksik paketler yeniden kurulacak.'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Cancel'", "'İptal'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Restore'", "'Geri Yükle'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Snapshot restored'", "'Anlık görüntü geri yüklendi'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Restore failed'", "'Geri yükleme başarısız oldu'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Restore failed: $error'", "'Geri yükleme başarısız oldu: $error'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Delete snapshot?'", "'Anlık görüntü silinsin mi?'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Delete'", "'Sil'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Desktop Tools'", "'Masaüstü Araçları'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Backups'", "'Yedekler'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'PINNED'", "'SABİTLENENLER'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'ADD AN ANDROID APP'", "'ANDROID UYGULAMASI EKLE'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Search installed apps'", "'Yüklü uygulamalarda ara'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Create desktop snapshot'", "'Masaüstü anlık görüntüsü oluştur'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'Backs up your Linux home, desktop settings, wallpaper and installed-package manifest.'", "'Linux ev dizininizi, masaüstü ayarlarınızı, duvar kâğıdınızı ve kurulu paket listenizi yedekler.'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'SNAPSHOTS'", "'ANLIK GÖRÜNTÜLER'"),
    ('app/lib/screens/desktop_tools_screen.dart', "'No snapshots yet'", "'Henüz anlık görüntü yok'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Installation Complete'", "'Kurulum Tamamlandı'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Installation Failed'", "'Kurulum Başarısız'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Configuring\\nLinux Workstation'", "'Linux İş İstasyonu\\nYapılandırılıyor'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Your Linux environment is ready.'", "'Linux ortamınız hazır.'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Downloading and configuring system packages.'", "'Sistem paketleri indiriliyor ve yapılandırılıyor.'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Extracting packages...'", "'Paketler çıkarılıyor...'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Return to Home'", "'Ana Sayfaya Dön'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Go Back'", "'Geri Dön'"),
    ('app/lib/screens/setup/de_install_screen.dart', "'Support Open Source'", "'Açık Kaynağı Destekle'"),
    ('app/lib/screens/setup/de_picker.dart', "'Fast, customizable, low resource usage. The best all-rounder.'", "'Hızlı, özelleştirilebilir, az kaynak tüketir. Her işe uygun en iyi seçenek.'"),
    ('app/lib/screens/setup/de_picker.dart', "'Ultra-lightweight Qt-based desktop. Fastest option.'", "'Son derece hafif, Qt tabanlı masaüstü. En hızlı seçenek.'"),
    ('app/lib/screens/setup/de_picker.dart', "'Classic GNOME 2 fork. Familiar and comfortable.'", "'Klasik GNOME 2 çatalı. Tanıdık ve rahat.'"),
    ('app/lib/screens/setup/de_picker.dart', "'Modern, feature-rich. Needs strong GPU and 4GB+ RAM.'", "'Modern ve zengin özellikli. Güçlü GPU ve 4 GB+ RAM gerektirir.'"),
    ('app/lib/screens/setup/de_picker.dart', "'Switch to Light Theme'", "'Açık temaya geç'"),
    ('app/lib/screens/setup/de_picker.dart', "'Switch to Dark Theme'", "'Koyu temaya geç'"),
    ('app/lib/screens/setup/de_picker.dart', "'Choose Desktop'", "'Masaüstü Seçin'"),
    ('app/lib/screens/setup/de_picker.dart', "'Desktop Essentials installs the selected desktop, terminal, file manager, and core tools. More apps can be added later.'", "'Temel Masaüstü Paketleri; seçilen masaüstünü, terminali, dosya yöneticisini ve temel araçları kurar. Diğer uygulamalar daha sonra eklenebilir.'"),
    ('app/lib/screens/setup/de_picker.dart', "'Back'", "'Geri'"),
    ('app/lib/screens/setup/de_picker.dart', "'Install Essentials'", "'Temel Paketleri Kur'"),
    ('app/lib/screens/setup/de_picker.dart', "'BEST'", "'EN İYİ'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Switch to Light Theme'", "'Açık temaya geç'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Switch to Dark Theme'", "'Koyu temaya geç'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Choose Your Linux'", "'Linux Dağıtımınızı Seçin'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Select a distribution to install. This will be downloaded on setup.'", "'Kurulacak dağıtımı seçin. Kurulum sırasında indirilecektir.'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Best overall experience. Huge package library, great community support.'", "'Genel olarak en iyi deneyim. Devasa paket arşivi, güçlü topluluk desteği.'"),
    ('app/lib/screens/setup/distro_picker.dart', "'~350 MB download'", "'~350 MB indirme'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Ultra minimal and secure. Best for low resource usage.'", "'Son derece minimal ve güvenli. Düşük kaynak kullanımı için ideal.'"),
    ('app/lib/screens/setup/distro_picker.dart', "'~3 MB download'", "'~3 MB indirme'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Security and pentesting tools. Wireshark, Metasploit, Nmap included.'", "'Güvenlik ve sızma testi araçları. Wireshark, Metasploit, Nmap dahil.'"),
    ('app/lib/screens/setup/distro_picker.dart', "'~500 MB download'", "'~500 MB indirme'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Back'", "'Geri'"),
    ('app/lib/screens/setup/distro_picker.dart', "'Next'", "'İleri'"),
    ('app/lib/screens/setup/distro_picker.dart', "'RECOMMENDED'", "'ÖNERİLEN'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Low storage'", "'Depolama alanı az'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Only $freeStorage MB is available. Desktop Essentials works best with at least 2 GB free. You can continue, but package installation may fail.'", "'Yalnızca $freeStorage MB boş alan var. Temel Masaüstü Paketleri en az 2 GB boş alanla en iyi şekilde çalışır. Devam edebilirsiniz, ancak paket kurulumu başarısız olabilir.'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Go back'", "'Geri dön'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Continue anyway'", "'Yine de devam et'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Root access detected'", "'Root erişimi algılandı'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Your device is rooted. Continue with the rooted chroot '", "'Cihazınız root\\'lu. En iyi performans ve tam Linux desteği için '"),
    ('app/lib/screens/setup/setup_progress.dart', "'runtime for the best performance and full Linux support?'", "'root\\'lu chroot çalışma ortamıyla devam edilsin mi?'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Cancel'", "'İptal'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Continue with root'", "'Root ile devam et'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Switch to Light Theme'", "'Açık temaya geç'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Switch to Dark Theme'", "'Koyu temaya geç'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Retry'", "'Tekrar Dene'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Launch DroidDesk'", "'DroidDesk\\'i Başlat'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Bootstrap environment'", "'Temel ortamı hazırla'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Configure package repositories'", "'Paket depolarını yapılandır'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Install Desktop Essentials'", "'Temel Masaüstü Paketlerini kur'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Finalize Desktop Essentials'", "'Temel Masaüstü kurulumunu tamamla'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Root access confirmed'", "'Root erişimi doğrulandı'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Download Ubuntu rootfs'", "'Ubuntu rootfs\\'i indir'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Install native packages'", "'Yerel paketleri kur'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Extract rootfs'", "'Rootfs\\'i çıkar'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Configure desktop'", "'Masaüstünü yapılandır'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Configure Linux'", "'Linux\\'u yapılandır'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Setup Failed'", "'Kurulum Başarısız'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Downloading'", "'İndiriliyor'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Preparing download...'", "'İndirme hazırlanıyor...'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Preparing Runtime'", "'Çalışma Ortamı Hazırlanıyor'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Installing Native Linux'", "'Yerel Linux Kuruluyor'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Preparing native Termux environment...'", "'Yerel Termux ortamı hazırlanıyor...'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Installing Desktop'", "'Masaüstü Kuruluyor'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Extracting'", "'Çıkarılıyor'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Extracting filesystem...'", "'Dosya sistemi çıkarılıyor...'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Setup Complete!'", "'Kurulum Tamamlandı!'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Your Linux desktop is ready to launch.'", "'Linux masaüstünüz başlatılmaya hazır.'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Setting Up'", "'Kuruluyor'"),
    ('app/lib/screens/setup/setup_progress.dart', "'Initializing...'", "'Başlatılıyor...'"),
    ('app/lib/state/app_state.dart', "'DroidDesk Linux Terminal\\nType commands below.\\n'", "'DroidDesk Linux Terminali\\nKomutları aşağıya yazın.\\n'"),
    ('app/lib/state/app_state.dart', "'Unknown GPU'", "'Bilinmeyen GPU'"),
    ('app/lib/state/app_state.dart', "'Failed to get runtime status: $e'", "'Çalışma ortamı durumu alınamadı: ${_hataMetni(e)}'"),
    ('app/lib/state/app_state.dart', "'Setup failed: $e'", "'Kurulum başarısız oldu: ${_hataMetni(e)}'"),
    ('app/lib/state/app_state.dart', "'Extracting native Termux bootstrap...'", "'Yerel Termux önyükleme paketi çıkarılıyor...'"),
    ('app/lib/state/app_state.dart', "'Bootstrap environment ready'", "'Temel ortam hazır'"),
    ('app/lib/state/app_state.dart', "'Native Termux package installation failed'", "'Yerel Termux paketleri kurulamadı'"),
    ('app/lib/state/app_state.dart', "'Downloading Ubuntu rootfs...'", "'Ubuntu rootfs indiriliyor...'"),
    ('app/lib/state/app_state.dart', "'Ubuntu download failed. Check your connection and retry.'", "'Ubuntu indirilemedi. Bağlantınızı kontrol edip tekrar deneyin.'"),
    ('app/lib/state/app_state.dart', "'Extracting rootfs...'", "'Rootfs çıkarılıyor...'"),
    ('app/lib/state/app_state.dart', "'Ubuntu filesystem extraction failed'", "'Ubuntu dosya sistemi çıkarılamadı'"),
    ('app/lib/state/app_state.dart', "'Installing desktop environment (this may take a while)...'", "'Masaüstü ortamı kuruluyor (bu biraz zaman alabilir)...'"),
    ('app/lib/state/app_state.dart', "'Desktop Essentials package installation failed'", "'Temel Masaüstü Paketleri kurulamadı'"),
    ('app/lib/state/app_state.dart', "'Extraction handled by setup flow'", "'Çıkarma işlemi kurulum akışında tamamlandı'"),
    ('app/lib/state/app_state.dart', "'Installing Desktop Environment...'", "'Masaüstü Ortamı Kuruluyor...'"),
    ('app/lib/state/app_state.dart', "'Installation failed: $e'", "'Kurulum başarısız oldu: ${_hataMetni(e)}'"),
    ('app/lib/state/app_state.dart', "'Preparing installation...'", "'Kurulum hazırlanıyor...'"),
    ('app/lib/state/app_state.dart', "'Linux runtime is not ready'", "'Linux çalışma ortamı hazır değil'"),
    ('app/lib/state/app_state.dart', "'Failed to start: $e'", "'Başlatılamadı: ${_hataMetni(e)}'"),
    ('app/lib/state/app_state.dart', "'Failed to launch desktop activity: $e'", "'Masaüstü ekranı açılamadı: ${_hataMetni(e)}'"),
    ('app/lib/state/app_state.dart', "'Failed to stop: $e'", "'Durdurulamadı: ${_hataMetni(e)}'"),
    ('app/lib/state/app_state.dart', '"Error executing command: $e"', '"Komut çalıştırılırken hata oluştu: ${_hataMetni(e)}"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Invalid package name"', '"Geçersiz paket adı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Repairing interrupted package operations..."', '"Yarım kalan paket işlemleri onarılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installation cancelled"', '"Kurulum iptal edildi"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing $packageName and dependencies..."', '"$packageName ve bağımlılıkları kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"$packageName installed"', '"$packageName kuruldu"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"$packageName installation failed"', '"$packageName kurulamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"This package is required by DroidDesk"', '"Bu paket DroidDesk için gereklidir"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Removing $packageName..."', '"$packageName kaldırılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Removal cancelled"', '"Kaldırma iptal edildi"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"$packageName removed"', '"$packageName kaldırıldı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"$packageName removal failed"', '"$packageName kaldırılamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Refreshing package repositories and retrying..."', '"Paket depoları yenileniyor ve yeniden deneniyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing lightweight PRoot runtime..."', '"Hafif PRoot çalışma ortamı kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Downloading minimal Debian base system..."', '"Minimal Debian temel sistemi indiriliyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Creating Debian shell shortcut..."', '"Debian kabuğu kısayolu oluşturuluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Minimal Debian compatibility is ready"', '"Minimal Debian uyumluluğu hazır"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"$selectedDesktop is already installed"', '"$selectedDesktop zaten kurulu"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Configuring X11 and TUR repositories..."', '"Tüm Termux depoları yapılandırılıyor (X11, TUR, root, glibc)..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Updating native package database..."', '"Yerel paket veritabanı güncelleniyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing X11 and audio packages..."', '"X11 ve ses paketleri kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing $selectedDesktop desktop packages..."', '"$selectedDesktop masaüstü paketleri kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing Mesa graphics packages..."', '"Mesa grafik paketleri kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing Adreno hardware acceleration..."', '"Adreno donanım hızlandırması kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing Desktop Essentials tools..."', '"Temel Masaüstü araçları kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Finalizing native Linux environment..."', '"Yerel Linux ortamı son haline getiriliyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Native Linux setup complete"', '"Yerel Linux kurulumu tamamlandı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Already installed"', '"Zaten kurulu"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Preparing relocated Node.js dependency..."', '"Node.js bağımlılığı hazırlanıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Repairing interrupted packages..."', '"Yarım kalan paketler onarılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing Firefox..."', '"Firefox kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing npm dependency..."', '"npm bağımlılığı kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing Code OSS..."', '"Code OSS kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing npm..."', '"npm kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installing ImageMagick..."', '"ImageMagick kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installation complete"', '"Kurulum tamamlandı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Installation failed. Review the package log and retry."', '"Kurulum başarısız oldu. Paket günlüğünü inceleyip tekrar deneyin."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Software (llvmpipe)"', '"Yazılımsal (llvmpipe)"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Root access required for chroot mode"', '"Chroot modu için root erişimi gerekli"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Rootfs not ready. Download and extract first."', '"Rootfs hazır değil. Önce indirip çıkarın."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Mounting rootfs..."', '"Rootfs bağlanıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Updating package lists..."', '"Paket listeleri güncelleniyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Package index update failed"', '"Paket dizini güncellenemedi"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Installing core tools..."', '"Temel araçlar kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Core package installation failed"', '"Temel paketler kurulamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Installing Mesa GPU drivers..."', '"Mesa GPU sürücüleri kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Installing desktop environment..."', '"Masaüstü ortamı kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Desktop package installation failed"', '"Masaüstü paketleri kurulamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Installing Desktop Essentials tools..."', '"Temel Masaüstü araçları kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Desktop Essentials package installation failed"', '"Temel Masaüstü Paketleri kurulamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Cleaning up..."', '"Temizleniyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"$desktopEnv installed in chroot"', '"$desktopEnv chroot içine kuruldu"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Installation failed: ${e.message}"', '"Kurulum başarısız oldu: ${e.message}"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Already installed"', '"Zaten kurulu"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Repairing interrupted packages..."', '"Yarım kalan paketler onarılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Installing optional application..."', '"İsteğe bağlı uygulama kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Package manager exited with code $exitCode"', '"Paket yöneticisi $exitCode koduyla sonlandı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Installation complete"', '"Kurulum tamamlandı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '"Installation failed: ${error.message}"', '"Kurulum başarısız oldu: ${error.message}"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Connecting to download server..."', '"İndirme sunucusuna bağlanılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"$distroName already downloaded"', '"$distroName zaten indirilmiş"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"$distroName downloaded successfully"', '"$distroName başarıyla indirildi"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Download failed: ${e.message}"', '"İndirme başarısız oldu: ${e.message}"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Downloading $distroName: ${downloadedMB}MB / ${totalMB}MB"', '"$distroName indiriliyor: ${downloadedMB} MB / ${totalMB} MB"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Rootfs tarball not found. Download first."', '"Rootfs arşivi bulunamadı. Önce indirin."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Extracting ${DISTRO_NAMES[distro]}..."', '"${DISTRO_NAMES[distro]} çıkarılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Extracting: $line"', '"Çıkarılıyor: $line"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Configuring Linux environment..."', '"Linux ortamı yapılandırılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"${DISTRO_NAMES[distro] ?: distro} setup complete"', '"${DISTRO_NAMES[distro] ?: distro} kurulumu tamamlandı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Extraction failed: ${e.message}"', '"Çıkarma başarısız oldu: ${e.message}"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Clearing package manager locks..."', '"Paket yöneticisi kilitleri temizleniyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Updating package lists..."', '"Paket listeleri güncelleniyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Configuring repositories..."', '"Depolar yapılandırılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Installing $de packages..."', '"$de paketleri kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Installing core utilities..."', '"Temel yardımcı programlar kuruluyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Configuring embedded X11 display..."', '"Gömülü X11 ekranı yapılandırılıyor..."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"$de installation complete!"', '"$de kurulumu tamamlandı!"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Installation failed: ${e.message}"', '"Kurulum başarısız oldu: ${e.message}"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootfsManager.kt', '"Apt-get failed: Check terminal output."', '"Apt-get başarısız oldu: Terminal çıktısını kontrol edin."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/RootShell.kt', '"No su binary found. Is this device rooted?"', '"su dosyası bulunamadı. Bu cihaz root\'lu mu?"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Home folder", "subtitle" to "Your Linux files", "source" to "Files"', '"label" to "Ev klasörü", "subtitle" to "Linux dosyalarınız", "source" to "Dosyalar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Downloads", "subtitle" to "Downloaded files", "source" to "Files"', '"label" to "İndirilenler", "subtitle" to "İndirilen dosyalar", "source" to "Dosyalar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Documents", "subtitle" to "Documents folder", "source" to "Files"', '"label" to "Belgeler", "subtitle" to "Belgeler klasörü", "source" to "Dosyalar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Pictures", "subtitle" to "Pictures folder", "source" to "Files"', '"label" to "Resimler", "subtitle" to "Resimler klasörü", "source" to "Dosyalar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Wi-Fi settings", "subtitle" to "Manage Android networks", "source" to "Settings"', '"label" to "Wi-Fi ayarları", "subtitle" to "Android ağlarını yönet", "source" to "Ayarlar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Bluetooth settings", "subtitle" to "Manage Android devices", "source" to "Settings"', '"label" to "Bluetooth ayarları", "subtitle" to "Android cihazlarını yönet", "source" to "Ayarlar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Display settings", "subtitle" to "Brightness and screen", "source" to "Settings"', '"label" to "Ekran ayarları", "subtitle" to "Parlaklık ve ekran", "source" to "Ayarlar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Sound settings", "subtitle" to "Volume and audio", "source" to "Settings"', '"label" to "Ses ayarları", "subtitle" to "Ses düzeyi ve ses", "source" to "Ayarlar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"label" to "Hotspot settings", "subtitle" to "Share mobile internet", "source" to "Settings"', '"label" to "Hotspot ayarları", "subtitle" to "Mobil interneti paylaş", "source" to "Ayarlar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"Could not preserve the current Linux home"', '"Mevcut Linux ev dizini korunamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/DesktopIntegration.kt', '"This snapshot belongs to a different Linux runtime mode"', '"Bu anlık görüntü farklı bir Linux çalışma modu için alınmış"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("home", "Home folder", homePath)', 'Triple("home", "Ev klasörü", homePath)'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("downloads", "Downloads",', 'Triple("downloads", "İndirilenler",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("documents", "Documents",', 'Triple("documents", "Belgeler",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("pictures", "Pictures",', 'Triple("pictures", "Resimler",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Comment=Open $label in Linux Files', "Comment=$label klasörünü Linux Dosyalar'da aç"),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("wifi", "Wi-Fi settings",', 'Triple("wifi", "Wi-Fi ayarları",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("bluetooth", "Bluetooth settings",', 'Triple("bluetooth", "Bluetooth ayarları",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("display", "Display and brightness",', 'Triple("display", "Ekran ve parlaklık",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("sound", "Sound and volume",', 'Triple("sound", "Ses ve ses düzeyi",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("hotspot", "Mobile hotspot",', 'Triple("hotspot", "Mobil hotspot",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Triple("battery", "Battery saver",', 'Triple("battery", "Pil tasarrufu",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/AndroidAppBridge.kt', 'Comment=Open Android $label', 'Comment=Android $label bölümünü aç'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/XfceMobileProfile.kt', 'comment = "Open the Linux terminal"', 'comment = "Linux terminalini aç"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/XfceMobileProfile.kt', 'name = "Files",', 'name = "Dosyalar",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/XfceMobileProfile.kt', 'comment = "Browse files"', 'comment = "Dosyalara göz at"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/XfceMobileProfile.kt', 'name = "Web Browser"', 'name = "Web Tarayıcı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/XfceMobileProfile.kt', 'comment = "Browse the web"', 'comment = "Web\'de gezin"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Auto-setup requires root"', '"Otomatik kurulum root gerektirir"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Rootfs download failed"', '"Rootfs indirilemedi"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Rootfs extraction failed"', '"Rootfs çıkarılamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Desktop installation failed"', '"Masaüstü kurulamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Auto-setup failed: ${e.message}"', '"Otomatik kurulum başarısız oldu: ${e.message}"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Software (llvmpipe)"', '"Yazılımsal (llvmpipe)"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Native Linux setup failed. Check the setup log."', '"Yerel Linux kurulumu başarısız oldu. Kurulum günlüğünü kontrol edin."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Previous package operation is still stopping. Try again."', '"Önceki paket işlemi hâlâ durduruluyor. Tekrar deneyin."'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Package operation failed"', '"Paket işlemi başarısız oldu"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"DroidDesk is already the default launcher"', '"DroidDesk zaten varsayılan başlatıcı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Choose your Home app"', '"Ana Ekran uygulamanızı seçin"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/MainActivity.kt', '"Android requires you to select another default Home app"', '"Android, başka bir varsayılan Ana Ekran uygulaması seçmenizi istiyor"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/service/DroidDeskService.kt', '"Linux desktop is running"', '"Linux masaüstü çalışıyor"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/service/DroidDeskService.kt', '"DroidDesk Linux Service"', '"DroidDesk Linux Hizmeti"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/service/DroidDeskService.kt', '"Keeps the Linux desktop environment running"', '"Linux masaüstü ortamının çalışmaya devam etmesini sağlar"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Waking up your portable Linux workspace"', '"Taşınabilir Linux çalışma alanınız uyandırılıyor"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Connecting Android to your Linux desktop"', '"Android, Linux masaüstünüze bağlanıyor"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Starting the desktop engine and services"', '"Masaüstü motoru ve hizmetleri başlatılıyor"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Loading your apps, icons, and shortcuts"', '"Uygulamalarınız, simgeleriniz ve kısayollarınız yükleniyor"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Polishing your panels, wallpaper, and workspace"', '"Paneller, duvar kâğıdı ve çalışma alanı hazırlanıyor"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Almost ready for your next big idea"', '"Bir sonraki büyük fikriniz için neredeyse hazır"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"About $remaining seconds remaining"', '"Yaklaşık $remaining saniye kaldı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Finishing up…"', '"Tamamlanıyor…"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Failed to attach LorieView to the X11 service"', '"LorieView, X11 hizmetine bağlanamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Drag desktop controls"', '"Masaüstü denetimlerini sürükle"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Input mode: $text"', '"Giriş modu: $text"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Hide desktop controls"', '"Masaüstü denetimlerini gizle"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Show desktop controls"', '"Masaüstü denetimlerini göster"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"Loading Linux desktop"', '"Linux masaüstü yükleniyor"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"About $estimatedLoadingSeconds seconds remaining"', '"Yaklaşık $estimatedLoadingSeconds saniye kaldı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/view/DesktopActivity.kt', '"X11 Error: $message"', '"X11 Hatası: $message"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11InputController.kt', '"Touchscreen"', '"Dokunmatik ekran"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11InputController.kt', '"Direct touch"', '"Doğrudan dokunma"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11InputController.kt', '"Trackpad"', '"Dokunmatik yüzey"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11ServiceClient.kt', '"The X11 service could not start the native server"', '"X11 hizmeti yerel sunucuyu başlatamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11ServiceClient.kt', '"The X11 service returned no client connection"', '"X11 hizmeti istemci bağlantısı döndürmedi"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11ServiceClient.kt', '"Failed to communicate with the X11 service"', '"X11 hizmetiyle iletişim kurulamadı"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11ServiceClient.kt', '"The X11 service process disconnected"', '"X11 hizmet süreci bağlantıyı kesti"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11ServiceClient.kt', '"The X11 service binding died"', '"X11 hizmet bağlantısı koptu"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11ServiceClient.kt', '"The X11 service returned a null binding"', '"X11 hizmeti boş bir bağlantı döndürdü"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/x11/X11ServiceClient.kt', '"Android refused the X11 service binding"', '"Android, X11 hizmet bağlantısını reddetti"')]

# (dosya, eski metin, yeni metin) — yapısal eklemeler (depolar, dil ayarları)
EKLEMELER = [('app/lib/state/app_state.dart', "import 'package:flutter/material.dart';\n", "import 'package:flutter/material.dart';\nimport 'package:flutter/services.dart';\n"),
    ('app/lib/state/app_state.dart', 'class AppState extends ChangeNotifier {\n', 'class AppState extends ChangeNotifier {\n  /// Hata nesnelerini kullanıcıya gösterilecek sade metne çevirir\n  /// ("Bad state: ..." veya "PlatformException(...)" önekleri olmadan).\n  static String _hataMetni(Object e) {\n    if (e is StateError) return e.message;\n    if (e is PlatformException) return e.message ?? e.code;\n    return e.toString();\n  }\n\n'),
    ('app/pubspec.yaml', 'description: "DroidDesk - Full Linux Desktop on Android"', 'description: "DroidDesk - Android\'de Tam Linux Masaüstü"'),
    ('app/pubspec.yaml', '  flutter:\n    sdk: flutter\n  google_fonts', '  flutter:\n    sdk: flutter\n  flutter_localizations:\n    sdk: flutter\n  google_fonts'),
    ('app/lib/main.dart', "import 'package:flutter/services.dart';\n", "import 'package:flutter/services.dart';\nimport 'package:flutter_localizations/flutter_localizations.dart';\n"),
    ('app/lib/main.dart', '      debugShowCheckedModeBanner: false,\n', "      debugShowCheckedModeBanner: false,\n      // Uygulama her zaman Türkçe: Flutter'ın yerleşik metinleri\n      // (Geri, Kopyala, Yapıştır, ipuçları vb.) de Türkçe gösterilir.\n      locale: const Locale('tr', 'TR'),\n      supportedLocales: const [Locale('tr', 'TR')],\n      localizationsDelegates: const [\n        GlobalMaterialLocalizations.delegate,\n        GlobalWidgetsLocalizations.delegate,\n        GlobalCupertinoLocalizations.delegate,\n      ],\n"),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '    private fun installRepoPackages(): Boolean {\n        val pkgs = listOf("x11-repo", "tur-repo")\n\n        // Ensure main package list is up to date before downloading the repo packages.\n        if (executeCommand("apt-get update").startsWith("Error:")) {\n            Log.e(TAG, "apt-get update failed before installing repo packages")\n            return false\n        }\n', '    /**\n     * Termux\'un tüm resmi depolarını etkinleştirir.\n     *\n     * - main      : önyükleme paketiyle zaten gelir\n     * - x11-repo  : grafik/masaüstü paketleri (zorunlu)\n     * - tur-repo  : Termux User Repository (zorunlu)\n     * - root-repo : root gerektiren araçlar (isteğe bağlı)\n     * - glibc-repo: glibc tabanlı paketler (isteğe bağlı)\n     *\n     * İsteğe bağlı depolardan biri kurulamazsa masaüstü kurulumu durdurulmaz,\n     * yalnızca günlüğe uyarı yazılır.\n     */\n    private fun installRepoPackages(): Boolean {\n        if (!installRepoPackageSet(listOf("x11-repo", "tur-repo"), refreshMainFirst = true)) {\n            return false\n        }\n        for (extraRepo in listOf("root-repo", "glibc-repo")) {\n            if (!isDpkgPackageInstalled(extraRepo) &&\n                !installRepoPackageSet(listOf(extraRepo), refreshMainFirst = false)\n            ) {\n                Log.w(TAG, "Optional repository $extraRepo could not be enabled; continuing")\n            }\n        }\n        return true\n    }\n\n    private fun installRepoPackageSet(pkgs: List<String>, refreshMainFirst: Boolean): Boolean {\n        // Ensure main package list is up to date before downloading the repo packages.\n        if (refreshMainFirst && executeCommand("apt-get update").startsWith("Error:")) {\n            Log.e(TAG, "apt-get update failed before installing repo packages")\n            return false\n        }\n'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Failed to download x11-repo/tur-repo .debs"', '"Failed to download ${pkgs.joinToString("/")} .debs"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Failed to unpack x11-repo/tur-repo .debs"', '"Failed to unpack ${pkgs.joinToString("/")} .debs"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"Failed to configure x11-repo/tur-repo"', '"Failed to configure ${pkgs.joinToString("/")}"'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '"apt", "bash", "coreutils", "dpkg", "termux-tools", "termux-am", "glibc-repo",\n            "x11-repo", "tur-repo",', '"apt", "bash", "coreutils", "dpkg", "termux-tools", "termux-am", "glibc-repo",\n            "x11-repo", "tur-repo", "root-repo",'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '            export NO_AT_BRIDGE=1\n            export GTK_A11Y=none\n            export DISPLAY=:0\n', "            export NO_AT_BRIDGE=1\n            export GTK_A11Y=none\n            export DISPLAY=:0\n\n            # Masaüstü arayüz dili: Türkçe (çeviri dosyası olmayan\n            # programlar İngilizce'ye döner)\n            export LANGUAGE=tr:en\n"),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '        onProgress?.invoke(0.9, "Debian kabuğu kısayolu oluşturuluyor...")\n', '        onProgress?.invoke(0.85, "Tüm Debian depo bileşenleri etkinleştiriliyor...")\n        enableAllDebianComponents()\n\n        onProgress?.invoke(0.9, "Debian kabuğu kısayolu oluşturuluyor...")\n'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/LinuxRuntime.kt', '    // ── Bootstrap ──\n', '    /**\n     * Debian konteynerinde main dışındaki tüm depo bileşenlerini\n     * (contrib, non-free, non-free-firmware) etkinleştirir. Dosyalar doğrudan\n     * düzenlenir; PRoot başlatılmaz. Hata kurulumu durdurmaz.\n     */\n    private fun enableAllDebianComponents() {\n        val allComponents = listOf("main", "contrib", "non-free", "non-free-firmware")\n        val rootfsDirs = listOf(\n            File(prefixDir, "var/lib/proot-distro/containers/debian/rootfs"),\n            File(prefixDir, "var/lib/proot-distro/installed-rootfs/debian"),\n        ).filter { it.isDirectory }\n        for (rootfs in rootfsDirs) {\n            try {\n                // deb822 biçimi (Debian 12+): "Components: main" satırları\n                val sourcesDir = File(rootfs, "etc/apt/sources.list.d")\n                sourcesDir.listFiles { f -> f.name.endsWith(".sources") }?.forEach { file ->\n                    val updated = file.readLines().joinToString("\\n") { line ->\n                        if (line.trimStart().startsWith("Components:")) {\n                            val existing = line.substringAfter("Components:").trim()\n                                .split(Regex("\\\\s+")).filter { it.isNotEmpty() }\n                            "Components: " + (existing + allComponents).distinct().joinToString(" ")\n                        } else line\n                    } + "\\n"\n                    file.writeText(updated)\n                }\n                // Klasik biçim: "deb <url> <suite> main" satırları\n                val listFile = File(rootfs, "etc/apt/sources.list")\n                if (listFile.isFile) {\n                    val updated = listFile.readLines().joinToString("\\n") { line ->\n                        val t = line.trim()\n                        if ((t.startsWith("deb ") || t.startsWith("deb-src ")) && !t.startsWith("#")) {\n                            val parts = t.split(Regex("\\\\s+"))\n                            // deb [seçenekler] url suite bileşen...\n                            val optEnd = if (parts.size > 1 && parts[1].startsWith("[")) {\n                                parts.indexOfFirst { it.endsWith("]") }\n                            } else 0\n                            val head = parts.take(optEnd + 3)\n                            val comps = parts.drop(optEnd + 3)\n                            if (optEnd < 0 || comps.isEmpty()) line\n                            else (head + (comps + allComponents).distinct()).joinToString(" ")\n                        } else line\n                    } + "\\n"\n                    listFile.writeText(updated)\n                }\n            } catch (error: Exception) {\n                Log.w(TAG, "Could not enable all Debian components in ${rootfs.absolutePath}", error)\n            }\n        }\n    }\n\n    // ── Bootstrap ──\n'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '            deb http://ports.ubuntu.com/ubuntu-ports noble-security main restricted universe multiverse\n', '            deb http://ports.ubuntu.com/ubuntu-ports noble-security main restricted universe multiverse\n            deb http://ports.ubuntu.com/ubuntu-ports noble-backports main restricted universe multiverse\n'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '                if (essentialsExit != 0) throw IllegalStateException("Temel Masaüstü Paketleri kurulamadı")\n', '                if (essentialsExit != 0) throw IllegalStateException("Temel Masaüstü Paketleri kurulamadı")\n\n                // Türkçe dil desteği: masaüstü menüleri ve uygulamalar Türkçe görünür.\n                // Başarısız olursa kurulum durmaz; arayüz İngilizce kalır.\n                onProgress(0.85, "Türkçe dil paketleri kuruluyor...")\n                val trExit = execChroot(\n                    "DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --no-install-recommends " +\n                            "language-pack-tr language-pack-gnome-tr",\n                    onLog\n                )\n                if (trExit != 0) Log.w(TAG, "Turkish language packs unavailable; desktop stays in English")\n                execChroot("locale-gen tr_TR.UTF-8 || true", onLog)\n'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '                # Locale\n                export LANG=C.UTF-8\n', '                # Locale: komut çıktıları C.UTF-8 kalır (betik uyumluluğu),\n                # masaüstü oturumu ayrıca Türkçe arayüz dilini kullanır.\n                export LANG=C.UTF-8\n'),
    ('app/android/app/src/main/kotlin/com/orailnoor/droiddesk/runtime/ChrootRuntime.kt', '            # Make sure X11 socket dir exists in case bind mount was late\n', "            # Masaüstü arayüz dili: Türkçe (tr_TR yerel ayarı üretilmişse)\n            if locale -a 2>/dev/null | grep -qi '^tr_TR\\.utf-\\?8${'$'}'; then\n                unset LC_ALL\n                export LANG=tr_TR.UTF-8\n                export LANGUAGE=tr:en\n                export LC_CTYPE=C.UTF-8\n            fi\n\n            # Make sure X11 socket dir exists in case bind mount was late\n")]

def uygula():
    degisen, atlanan, eksik = 0, 0, []
    dosyalar = {}
    def oku(yol):
        if yol not in dosyalar:
            if not os.path.isfile(yol):
                return None
            with open(yol, encoding="utf-8") as f:
                dosyalar[yol] = f.read()
        return dosyalar[yol]
    for tur, liste in (("ceviri", CEVIRILER), ("ekleme", EKLEMELER)):
        for yol, eski, yeni in liste:
            s = oku(yol)
            if s is None:
                eksik.append((yol, "(dosya yok)"))
                continue
            if tur == "ceviri":
                if eski in s:
                    dosyalar[yol] = s.replace(eski, yeni); degisen += 1
                elif yeni in s:
                    atlanan += 1
                else:
                    eksik.append((yol, eski))
            else:
                if yeni in s:
                    atlanan += 1
                elif eski in s:
                    dosyalar[yol] = s.replace(eski, yeni, 1); degisen += 1
                else:
                    eksik.append((yol, eski))
    for yol, s in dosyalar.items():
        with open(yol, "w", encoding="utf-8") as f:
            f.write(s)
    print(f"Uygulanan değişiklik: {degisen}")
    print(f"Zaten uygulanmış (atlandı): {atlanan}")
    if eksik:
        print(f"UYARI - bulunamayan {len(eksik)} metin (depodaki kod farklı olabilir):")
        for yol, eski in eksik:
            ilk = eski.strip().splitlines()[0][:90] if eski.strip() else eski
            print(f"  - {yol}: {ilk}")
    return 0

if __name__ == "__main__":
    sys.exit(uygula())
